### ISSUE TITLE
Multi-Monitor Support

### ISSUE THREAD

**Issue by Nox13last** [openrecall/openrecall#15]
From what I'm seeing, there's really good stuff so far. However, I use two screens. My left is my primary one and the one I do all my work on. My right is my secondary screen, which is used for media like YouTube, Twitch, or music players.
OpenRecall is only capturing my secondary screen. Would it be possible for it to capture all monitors, or else configure which screen it monitors?

Using Windows 11. Python 3.11.0 (as instructed in readme.md, lacking any specific subversion.)

**Comment by martinszeltins** [comment]
I use 3 monitors and I do work on all 3 of them.

**Comment by koenvaneijk** [comment]
Thank you @Nox13last for your suggestion. This is indeed important. We are currently only capturing the primary monitor. I will update this issue to track progress, as we have added this to the roadmap.

**Comment by koenvaneijk** [comment]
## Feature: Multi-Monitor Support

### Description

OpenRecall currently captures and processes digital history from a single monitor. To enhance the utility and usability of OpenRecall, we propose adding multi-monitor support. This feature will allow OpenRecall to simultaneously capture screenshots from multiple monitors, ensuring that users with multi-monitor setups can fully leverage the software's capabilities. 

### Goals

- **Simultaneous Capture**: Enable OpenRecall to take screenshots of all active monitors at regular intervals.
- **Unified Search**: Integrate the captured data from all monitors into a single searchable database, allowing users to find information regardless of which monitor it was on.
- **Efficient Storage**: Optimize storage mechanisms to handle the increased data from multiple monitors without significantly impacting performance or storage space.
- **User Configuration**: Provide options for users to configure which monitors are included in the capture process, offering flexibility based on individual needs and preferences.

### Implementation Steps

1. **System Detection**: Enhance the application to detect and list all connected monitors.
2. **Capture Mechanism**: Modify the screenshot capture process to handle multiple monitors, ensuring synchronized capture across all screens.
3. **Data Management**: Adjust the data storage and indexing system to accommodate multi-monitor data while maintaining efficient performance.
4. **User Interface**: Update the settings interface to allow users to select and configure the monitors they want to include in the capture process.
5. **Testing**: Conduct thorough testing across different multi-monitor setups to ensure compatibility and performance.

### Benefits

- **Comprehensive Coverage**: Users with multi-monitor setups can capture and search their complete digital history without missing any information displayed on secondary monitors.
- **Improved Productivity**: Facilitates better memory recall and productivity by ensuring that all digital interactions are documented and searchable.
- **Customization**: Users have the flexibility to include or exclude monitors based on their specific needs, providing a tailored experience.

### Potential Challenges

- **Performance Impact**: Capturing screenshots from multiple monitors may impact system performance. Optimization techniques will be essential to minimize any negative effects.
- **Storage Requirements**: Increased data from multiple monitors will require more storage. Efficient data compression and management strategies will be necessary.

**Comment by Nox13last** [comment]
Just updated. It looks like the first screenshot the program took upon launching captured both monitors. However, subsequent ones are back to using the primary monitor.
Seeing it in action (however inadvertently) has highlighted a bit of a problem. In _my_ case, my primary monitor is in 4K, and the secondary monitor is 1080. The ratio between the two monitors is funny to look at, but the combined size makes the secondary monitor practically microscopic! 

Good stuff on the horizon, though. Looking forward to working with it.

**Comment by koenvaneijk** [comment]
Multi-monitor support was added to version 0.3! There's also a new argument `--primary-monitor-only` which does what it says.
