### ISSUE TITLE
Windows Install Issues

### ISSUE THREAD

**Issue by SoundedSquash** [openrecall/openrecall#20]
There are 3 errors I'm encountering, and there may be more.

Include python-doctr on pip install.
Include requirement for GTK Runtime
Fix torch compatibility

Problem 1:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openrecall\app.py", line 9, in <module>
    from doctr.models import ocr_predictor
ModuleNotFoundError: No module named 'doctr'

Fix:
pip install python-doctr

Problem 2:
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

Fix:
Install [GTK-for-Windows-Runtime-Environment-Installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer)

Problem 3:
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\lib\shm.dll" or one of its dependencies.

Fix:
None yet. I tried downgrading to torch 2.2.1, but dependencies don't allow that. Running the app anyway just shows a terminal new line and the localhost site doesn't work.

**Comment by SoundedSquash** [comment]
I was able to fix torch by modying the __init__.py following this commit https://github.com/pytorch/pytorch/commit/fdfef759a676ee7a853872e347537bc1e4b51390

**Comment by SoundedSquash** [comment]
The final thing I had to do was `pip install psutil`. Then it was able to run.

I'm not sure if this has to do with using the Microsoft Store version of Python, but these problems/fixes should be included in the install (pip installs) or readme (GTK).

**Comment by RudiKlein** [comment]
@SoundedSquash I first tried to install on the Store Python, but that failed completely. I've removed all Store versions of Python, installed Python 3.12 from python.org and I still had to apply all the fixes mentioned above except for the Pytorch error.
It seems when GTK, python-doctr and psutil are installed, all works fine.

**Comment by koenvaneijk** [comment]
We see a lot of Windows users, like yourself, experience installation issues, therefore I've created issue #22 and added it to the roadmap. The one-click installer should include all dependencies (such as an embedded Python) in a single one-click installer. We believe this feature is top priority, right after the encryption of storage.

**Comment by koenvaneijk** [comment]
I pushed a small fix where `psutil` would not be installed on the Windows platform by default. It was included in the `requirements.txt` but not in the `setup.py`. This should install `psutil` on Windows when running from `pip` command.

**Comment by koenvaneijk** [comment]
This issue was caused by PyTorch 2.3+ on Windows. I've updated the `setup.py` to use PyTorch 2.2.1 which correctly places the `shm.dll` on Windows. Let me know if anyone here is still facing this issue.
