### ISSUE TITLE
refactoring/improvements

### ISSUE THREAD

**Issue by iaacornus** [openrecall/openrecall#21]
i browsed the src code, the code is good but i think i can help in improving the code a little more if its fine

**Comment by koenvaneijk** [comment]
@iaacornus thank you for your offer. We are happy to receive any feedback either in issue form or pull request!

**Comment by koenvaneijk** [comment]
@iaacornus I'm closing this issue for now as it is not directly related to a feature or bug. If you would like to share any code contributions, feel free to submit a pull request.

**Comment by iaacornus** [comment]
> @iaacornus I'm closing this issue for now as it is not directly related to a feature or bug. If you would like to share any code contributions, feel free to submit a pull request.

okay, i have already started a little work on it actually, just message me if u want it continued
