### ISSUE TITLE
Support Wayland on Linux

### ISSUE THREAD

**Issue by lavafroth** [openrecall/openrecall#27]
We are currently using `mss` for taking screenshots and while that works on X11, a lot of Linux users are driving Wayland. Trying out the vanilla implementation in this repo causes this error on Wayland:

```
File "/home/h/Public/openrecall_venv/.direnv/python-3.11/lib/python3.11/site-packages/mss/linux.py", line 297, in __init__
    raise ScreenShotError("No X11 library found.")
mss.exception.ScreenShotError: No X11 library found.
```

[pyscreenshot](https://github.com/ponty/pyscreenshot) claims to have Wayland support. I can confirm this and we can possibly replace mss with it. However, I'm not sure about a multi-monitor setup. It'd be great if someone else could test it out.

**Comment by koenvaneijk** [comment]
Hi @lavafroth thank you for raising this. There's another issue #10 about this, I will close this one to keep the discussion centralized. We've put it on the short term roadmap to support Wayland.
