### ISSUE TITLE
[Feature Request] Specify DB storage path and Image storage path

### ISSUE THREAD

**Issue by Some1OnLine** [openrecall/openrecall#34]
I can see many images being generated over time and eating up a lot of storage. would be nice to be able to point image storage to a location other than user profile path where storage might be limited.  Maybe some basic settings via conf file or web GUI.

I'm definitely keeping my eye on this project. Im no dev. but will definitely buy you a beer!

**Comment by koenvaneijk** [comment]
@Some1OnLine I've added the argument `--storage-path` to v0.3 in `main` branch which allows you to specify the storage path. Default is your OS user data folder for the app.

**Comment by Some1OnLine** [comment]
Thank you!
