### ISSUE TITLE
License Change Request: Move from AGPL to a More Permissive License (e.g., MIT or Apache 2.0)

### ISSUE THREAD

**Issue by samj** [openrecall/openrecall#50]
*OpenRecall has been proposed for packaging in the MIT-licensed pAI-OS, being built by the 501(c)(3) charity Kwaai. I don't think it's an issue but I don't want to waste lawyer cycles on deciding whether it is or not, knowing we're unlikely to get a clear answer either way. I also don't want to give our users any reason to skip over us too. I was planning on implementing the feature anyway and may yet do that, but figured I can't be upset with the decision if you never hear my objection. I've been an active participant in the open source ecosystem for decades and totally understand why the (at this point arguably failed) AGPL was introduced - also being an early proponent of cloud computing - but it makes no sense whatsoever in this context because if I convey the software to you I'd already be triggering the GPL's teeth, and nobody in their right mind is about to give network access to this to third-parties for which the AGPL would be relevant! Please reconsider. - samj*

OpenRecall is a powerful tool for logging screen activity to a local SQLite database, offering significant utility for personal and professional projects alike. However, its current license (AGPL) presents substantial challenges and limitations that could impede wider adoption and use, particularly in personal or non-service provider scenarios.

**Concerns with AGPL License:**

- **Unnecessary Restriction for Individual Use:** The AGPL was designed to address the "service provider loophole," ensuring modifications and improvements are shared back with the community. While this is beneficial for server-side software and services, OpenRecall is primarily intended for individual use. The stringent requirements of the AGPL do not provide additional benefits in this context and instead introduce unnecessary legal and operational complexities for users.
- **Deterrent to Adoption:**
The AGPL can be a strong deterrent for developers and organizations considering incorporating OpenRecall into their workflows or products. The obligation to disclose source code modifications and network usage details under AGPL is seen as overly burdensome and can discourage contributions, integrations, and broader community support.
- **Compatibility Issues:** Many open-source projects use more permissive licenses (e.g., MIT, Apache 2.0) that are more compatible with a variety of other software. The AGPL's requirements can create conflicts, preventing seamless integration with other tools and libraries. This limits the potential for OpenRecall to be part of larger ecosystems or combined with other open-source projects.

**Suggested Action:**
To foster a more inclusive and flexible environment for OpenRecall, we propose changing the license to a more permissive one, such as MIT or Apache 2.0. These licenses offer several advantages:

- **Ease of Use**: Simplifies the legal and operational aspects for individual users and developers.
- **Encourages Contributions**: Lowers the barrier to entry for contributions and integrations, fostering a larger and more vibrant community.
- **Greater Compatibility**: Facilitates integration with other open-source projects and tools, enhancing the overall utility and appeal of OpenRecall.

**Conclusion:**

While the AGPL license has its merits, it imposes significant constraints that are not aligned with the primary use case of OpenRecall. Adopting a more permissive license would remove these barriers, promoting wider adoption, ease of use, and community engagement. We believe this change would significantly enhance the value and impact of OpenRecall, aligning with the broader goals of openness and collaboration in the open-source community.

We look forward to the community's feedback and hope for a constructive discussion on this important matter.

Thank you for your consideration.

**Comment by koenvaneijk** [comment]
Hi @samj, thanks for sharing your feedback and concerns. At the moment we are not reconsidering the license for OpenRecall. This does not mean we will never consider releasing it under a different, such as a more permissive, license in the future.

As this issue is not about a feature or bug, I will close it for now. It is critical however that any matter can be discussed by the community and therefore I do invite you to repost your invitation to discussion here: https://github.com/openrecall/openrecall/discussions

**Comment by samj** [comment]
Thanks for the prompt response.

I do hope you revisit this issue soon and have posted a poll to see what others think: https://github.com/openrecall/openrecall/discussions/51
