### ISSUE TITLE
OpenRecall should ignore screen saver

### ISSUE THREAD

**Issue by Korayem** [openrecall/openrecall#52]
It's taking a lot of meaningless screenshots :)

Another issue is that when I search, it matches a lot of those screensaver screenshots although they're just photos of trees :)
<img width="1375" alt="image" src="https://github.com/openrecall/openrecall/assets/198332/5e9a9941-afe2-4094-af0e-c4e12de7fd9c">

**Comment by koenvaneijk** [comment]
Thank you for your suggestion. I've taken this a bit broader to "user idle check" and created issue #60 with a detailed description. Eager to hear your feedback.
