### ISSUE TITLE
min. hardware requirements

### ISSUE THREAD

**Issue by Golddouble** [openrecall/openrecall#54]
Would the following PC be new/fast enough to operate openrecall?:
```
CPU: quad core Intel Core i5-4570 (-MCP-) speed/min/max: 837/800/3201 MHz
RAM: 15895.7 MiB
Storage: 2.17 TiB
Graphics:  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics
    vendor: Hewlett-Packard driver: i915 v: kernel arch: Gen-7.5 process: Intel 22nm built: 2013
    ports: active: VGA-1 empty: DP-1, DP-2, HDMI-A-1, HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:0412
    class-ID: 0300[/CODE]
No graphical card.
```

I mean, if it takes all 5 seconds a screenshot and has to OCR it with text and picture: With this hardware: Is not all the time GPU and CPU at 100% ?

Thank you.

**Comment by koenvaneijk** [comment]
Please let us know if you are having issues with this hardware. I've added a `hardware.md` to keep track of this:

https://github.com/openrecall/openrecall/commit/3f8c25f0ef89474d33cc43d31f848c8f8f014bae

Feel free to submit a pull request after your testing, thank you!

Closing this for now as it is not related to a feature or a bug.
