### ISSUE TITLE
suggestion: exe version

### ISSUE THREAD

**Issue by furllmm** [openrecall/openrecall#58]
title

**Comment by Nox13last** [comment]
Make a .BAT.
```
@echo off
title OpenRecall Updater
pip install --upgrade --no-cache-dir git+https://github.com/openrecall/openrecall.git
title OpenRecall
cls
python3 -m openrecall.app
```

**Comment by furllmm** [comment]
ty 
where is data path

**Comment by Nox13last** [comment]
You mean where the database is and where the screenshots are kept?
That's `%AppData%\openrecall\`  (or `C:\Users\[Your Username]\AppData\Roaming\openrecall`)

**Comment by koenvaneijk** [comment]
This is on our roadmap! Closing this as it is a duplicate of #22
